# Generated by Django 2.2.3 on 2019-08-13 12:23

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_django', '0002_auto_20190731_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangomodel',
            name='slug',
            field=models.SlugField(default=12, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='djangomodel',
            name='textDjango',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
