# Generated by Django 2.2.3 on 2019-08-05 08:46

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleProg', models.CharField(max_length=200, verbose_name='titleProg')),
                ('storyPrograms', models.TextField(default='', verbose_name='Расширенное описание, функционал и т.д')),
                ('previewPrograms', models.ImageField(upload_to='', verbose_name='Каритинка 260х180')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titleProg')),
                ('languegesPrograms', models.TextField(default='', verbose_name='языки которые поддерживает программа')),
                ('demandPrograms', models.TextField(default='', verbose_name='Требования')),
                ('memoryPrograms', models.TextField(default='', verbose_name='Место, на жестком диске')),
                ('uploadPrograms', models.TextField(default='', verbose_name='Сыллка с установкой')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Программы',
                'verbose_name_plural': 'Программы',
            },
        ),
    ]
