# Generated by Django 2.2.3 on 2019-08-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
