# Generated by Django 2.2.3 on 2019-08-13 12:22

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20190805_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='storyPrograms',
            field=djrichtextfield.models.RichTextField(default='', verbose_name='Расширенное описание, функционал и т.д'),
        ),
    ]
