# Generated by Django 2.2.3 on 2019-08-18 03:08

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20190813_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programs',
            options={'ordering': ['-date'], 'verbose_name': 'Программы', 'verbose_name_plural': 'Программы'},
        ),
        migrations.RenameField(
            model_name='programs',
            old_name='titleProg',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='programs',
            name='storyPrograms',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
