# Generated by Django 2.2.3 on 2019-08-03 12:33

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(default='')),
                ('dates', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-dates'],
            },
        ),
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=3000, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(default='default_value', upload_to='', verbose_name='Каритинка 260х180')),
                ('article_like', models.IntegerField(default='0')),
                ('article_dislike', models.IntegerField(default='0')),
                ('view', models.IntegerField(default='0')),
                ('datesArticle', models.DateTimeField(auto_now=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-datesArticle'],
            },
        ),
    ]
