# Generated by Django 2.2.3 on 2019-08-04 04:36

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=13, editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
