# Generated by Django 2.2.3 on 2019-08-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_articles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.CharField(blank=True, max_length=200, verbose_name='Транслит'),
        ),
    ]
