# Generated by Django 2.2.3 on 2019-08-04 05:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190804_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
