# Generated by Django 2.2.3 on 2019-08-12 15:58

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190804_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='post',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
