# Generated by Django 2.2.3 on 2019-07-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JarComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameJar', models.CharField(max_length=100)),
                ('textCommentJar', models.TextField(default='')),
                ('datesCommentJar', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-datesCommentJar'],
            },
        ),
        migrations.CreateModel(
            name='JarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleJar', models.CharField(max_length=400, verbose_name='Названия')),
                ('textJar', models.TextField(verbose_name='Текст')),
                ('datesJar', models.DateTimeField(auto_now=True)),
                ('viewJar', models.IntegerField(default=0)),
                ('imgJar', models.ImageField(default='default_value', upload_to='JavaLessonsImagae')),
                ('jar_like', models.IntegerField(default=0)),
                ('jar_dislike', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-datesJar'],
            },
        ),
    ]
