# Generated by Django 2.2.3 on 2019-07-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_java', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jarmodel',
            name='imgJar',
            field=models.ImageField(default='default_value', upload_to='JavaLessonsImagae', verbose_name='Каритинка 260х180'),
        ),
    ]
