# Generated by Django 2.2.3 on 2019-08-22 15:36

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleC', models.CharField(max_length=400, verbose_name='Названия')),
                ('textC', djrichtextfield.models.RichTextField()),
                ('datesC', models.DateTimeField(auto_now=True)),
                ('viewC', models.IntegerField(default=0)),
                ('imgC', models.ImageField(default='default_value', upload_to='CLessonsImagae', verbose_name='Каритинка 260х180')),
                ('C_like', models.IntegerField(default=0)),
                ('C_dislike', models.IntegerField(default=0)),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['-datesC'],
            },
        ),
    ]
